services:
  backend:
    build:
      context: .
      args:
        - CUSTOM_ARG=custom_value
      dockerfile: Dockerfile
    image: ${APP_NAME}:1.0
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_URL=http://localhost:8080
      - DB_HOST=db
      - DB_CONNECTION=mysql
      - DB_PORT=3306
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_TIMEZONE=${APP_TIMEZONE}
      - APP_URL=${APP_URL}
      - APP_LOCALE=${APP_LOCALE}
      - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE}
      - APP_FAKER_LOCALE=${APP_FAKER_LOCALE}
      - APP_MAINTENANCE_DRIVER=${APP_MAINTENANCE_DRIVER}
      - APP_MAINTENANCE_STORE=${APP_MAINTENANCE_STORE}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - LOG_STACK=${LOG_STACK}
      - LOG_DEPRECATIONS_CHANNEL=${LOG_DEPRECATIONS_CHANNEL}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_LIFETIME=${SESSION_LIFETIME}
      - SESSION_ENCRYPT=${SESSION_ENCRYPT}
      - SESSION_PATH=${SESSION_PATH}
      - SESSION_DOMAIN=${SESSION_DOMAIN}
      - BROADCAST_CONNECTION=${BROADCAST_CONNECTION}
      - FILESYSTEM_DISK=${FILESYSTEM_DISK}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - CACHE_STORE=${CACHE_STORE}
      - CACHE_PREFIX=${CACHE_PREFIX}
      - MEMCACHED_HOST=${MEMCACHED_HOST}
      - REDIS_CLIENT=${REDIS_CLIENT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}
      - VITE_APP_NAME=${VITE_APP_NAME}
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
