services:

  caddy:
    image: caddy:2-alpine
    container_name: caddy_reverse_proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build:
      context: .
      args:
        - CUSTOM_ARG=custom_value
      dockerfile: Dockerfile
    container_name: mycontainer
    ports:
      - "8080:8080"
    depends_on:
      pgdb:
        condition: service_healthy
    environment:
      - APP_URL=http://localhost:8080
      - ASSET_URL=http://localhost:8080
      - DB_HOST=pgdb
      - DB_CONNECTION=pgsql
      - DB_PORT=5432
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_TIMEZONE=${APP_TIMEZONE}
      - APP_LOCALE=${APP_LOCALE}
      - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE}
      - APP_FAKER_LOCALE=${APP_FAKER_LOCALE}
      - APP_MAINTENANCE_DRIVER=${APP_MAINTENANCE_DRIVER}
      - APP_MAINTENANCE_STORE=${APP_MAINTENANCE_STORE}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - LOG_STACK=${LOG_STACK}
      - LOG_DEPRECATIONS_CHANNEL=${LOG_DEPRECATIONS_CHANNEL}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_LIFETIME=${SESSION_LIFETIME}
      - SESSION_ENCRYPT=${SESSION_ENCRYPT}
      - SESSION_PATH=${SESSION_PATH}
      - SESSION_DOMAIN=${SESSION_DOMAIN}
      - BROADCAST_CONNECTION=${BROADCAST_CONNECTION}
      - FILESYSTEM_DISK=${FILESYSTEM_DISK}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - CACHE_STORE=${CACHE_STORE}
      - CACHE_PREFIX=${CACHE_PREFIX}
      - MEMCACHED_HOST=${MEMCACHED_HOST}
      - REDIS_CLIENT=${REDIS_CLIENT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}
      - VITE_APP_NAME=${VITE_APP_NAME}
    networks:
      - app-network

  pgdb:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #PGDATA: /data/postgres
    volumes:
      - pgdb:/var/lib/postgresql
    ports:
      - "5433:5432"
    expose:
      - '5432'
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app-network
    restart: unless-stopped

volumes:
    pgdb:
    pgadmin:
    caddy_data:
    caddy_config:

networks:
  app-network:
    driver: bridge
